schema_version = "1.0.0"

id = "Wal_Theme"
version = "1.0.0"
name = "Wallpaper Theme"
tagline = "Apply Wallpaper Colors to Blender Theme"
maintainer = "Ctoagn1 <qwezese@gmail.com>"
type = "add-on"

website = "https://github.com/Ctoagn1/blender-wal/"

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

[permissions]
files = "Reads wallpaper file and writes to themes"

